### ISSUE TITLE
proc List

### ISSUE THREAD

**Issue by czdiao** [yu961549745/VSCodeHighlightForMaple#1]
Hi Jiangtao,

Thanks for making such a useful extension for maple!

Since I keep long mpl files defining a lot of proc(), which is not easy to navigate. I am wondering if you could add the feature of a proc list to this vscode extension? I checked multiple editors that have extensions for Maple, but didn't find anyone with this feature. Thanks!

**Comment by yu961549745** [comment]
Thanks for your advice. 
I'll try it in the near future.

**Comment by yu961549745** [comment]
The extension has been updated.
Welcome to update.
